name: Binary releases

on:
    push:
        tags:
            - '*'
    workflow_dispatch:

jobs:
    build:
        name: Build for ${{ matrix.platform }} (${{ matrix.arch }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - alpine
                    - linux
                    - linuxstatic
                    - win
                    - macos
                arch:
                    - x64
                    - arm64

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Build source
              run: npm run build:js

            - name: Build binary
              run: npx pkg dist/index.js -o output.exe --scripts dist/**/*.js --targets node16-${{ matrix.platform }}-${{ matrix.arch }}

            - name: Upload
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.platform }}-${{ matrix.arch }}
                  path: output.exe
